name: C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install build environment
        run: sudo apt install -y build-essential cmake  ninja-build
      - name: Configure
        run: cmake -B build -G Ninja
      - name: Build
        run: cmake --build build -t all
      - name: Test
        run: ctest --test-dir build